apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: default
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello
    ports:
    - containerPort: 3000
    resources:
      requests:
        ephemeral-storage: "1Gi"
        memory: "500Mi"
        cpu: "100m"
      limits:
        ephemeral-storage: "2Gi"
        memory: "500Mi"
    volumeMounts:
    - name: config
      mountPath: /var/log
  volumes:
  - name: config
    emptyDir: {}

