apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: nginx:1.21.6
    volumeMounts:
    - name: app-storage
      mountPath: /data/config
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: db-pvc
