apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello
    ports:
    - containerPort: 3000
      name: nodejs-port
    resources: {}
    readinessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 2
      periodSeconds: 8
  restartPolicy: Never
