apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    tier: backend
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - image: nginx:1.23.4-alpine
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
