apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-15T16:54:18Z"
  name: service-list
  namespace: t23
spec:
  serviceAccountName: api-call
  containers:
  - image: alpine/curl:3.14
    name: service-list
    command: ['sh', '-c', 'while true; do curl -s -k -m 5 -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/t23/pods; sleep 10; done']
