apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: default
spec:
  containers:
  - image: nginx:1.23.4-alpine
    name: server
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: config
      mountPath: /etc/config
  volumes:
  - name: config
    configMap:
      name: app-config
